# Generated by Django 2.1.7 on 2019-04-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190430_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='viewed_by',
            field=models.TextField(default=''),
        ),
    ]
