# Generated by Django 2.1.7 on 2019-05-07 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_kid_grupa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Przedszkolak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_skrócona', models.CharField(max_length=20, unique=True)),
                ('Imię', models.CharField(max_length=20)),
                ('Nazwisko', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Przedszkolak',
            },
        ),
        migrations.RemoveField(
            model_name='kid',
            name='grupa',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='parent',
        ),
        migrations.AlterModelOptions(
            name='grupa',
            options={'verbose_name_plural': 'Grupy'},
        ),
        migrations.AlterField(
            model_name='grupa',
            name='nazwa',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Kid',
        ),
        migrations.AddField(
            model_name='przedszkolak',
            name='grupa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Grupa'),
        ),
        migrations.AddField(
            model_name='przedszkolak',
            name='rodzic',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
