# Generated by Django 2.1.7 on 2019-05-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190507_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='przedszkolak',
            options={'verbose_name_plural': 'Przedszkolaki'},
        ),
    ]
